### ISSUE TITLE
Command Validator fails to validate

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#1022]
**What happened**:

Due to a backwards-incompatible change introduced in the `data-schema`, the `screwdriver-command-validator` no longer works. 

**What you expected to happen**:

The `screwdriver-command-validator` to validate a proper `command.yaml`.

**How to reproduce it**:

Commands:
   * `docker run --rm -ti --entrypoint=/bin/bash node:8`
   * `npm i -g screwdriver-command-validator`
   * `command-validate -f ./sd-command.yaml`

Example: 

```
$ docker run --rm -ti --entrypoint=/bin/bash node:8
$ npm i -g screwdriver-command-validator
/usr/local/bin/command-validate -> /usr/local/lib/node_modules/screwdriver-command-validator/validate.js
+ screwdriver-command-validator@1.0.4
added 12 packages in 1.106s
$ command-validate -f ./sd-command.yaml
/usr/local/lib/node_modules/screwdriver-command-validator/node_modules/screwdriver-data-schema/plugins/scm.js:9
const hook = Joi.reach(core.scm.hook, '').required();
                                         ^

TypeError: Cannot read property 'required' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/screwdriver-command-validator/node_modules/screwdriver-data-schema/plugins/scm.js:9:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/screwdriver-command-validator/node_modules/screwdriver-data-schema/plugins/index.js:6:13)
    at Module._compile (module.js:652:30)

$ npm --version
5.6.0
$ node --version
v8.10.0
```

**Comment by minz1027** [comment]
This is because `joi` just published a new release 9 hours ago that doesn't work with our current code `Joi.reach(core.scm.hook, '').required();`.

**Comment by minz1027** [comment]
it's fixed now by this PR https://github.com/screwdriver-cd/data-schema/commit/87832061ee9e6b21df3e6f281dfd689c4a2c22b2
