### ISSUE TITLE
Uncaught error: this._next is not a function

### ISSUE THREAD

**Issue by ebarriosjr** [screwdriver-cd/screwdriver#2341]
**What happened**:
After installing the app and login via github scm no page works. I get the error:
`Uncaught error: this._next is not a function`
On every call to the api backend. Example calls that return a 500:
- http://screwdriver-api.my-domain/v4/collections
- http://screwdriver-api.my-domain/v4/templates?sortBy=createTime&sort=descending&compact=true

**What you expected to happen**:
I expected the api to answer with a 200 and return data.

**How to reproduce it**:
I am pulling the latest docker container and addding a config for each one of the components.
The real error output inside the api is:
```
210208/114150.525, (1612784510137:69693c741a8f:29:kkwi8iof:10006) [request,server,error] data: TypeError: Uncaught error: this._next is not a function
    at Function.internals.continue (/usr/src/app/node_modules/hapi/lib/reply.js:139:10)
    at bound (domain.js:426:14)
    at Function.runBound [as continue] (domain.js:439:12)
    at /usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:176:39
    at Object.validateFunc (/usr/src/app/node_modules/screwdriver-api/plugins/auth/index.js:176:21)
    at /usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:166:34
    at /usr/src/app/node_modules/hapi-auth-jwt2/node_modules/jsonwebtoken/verify.js:223:12
    at getSecret (/usr/src/app/node_modules/hapi-auth-jwt2/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/usr/src/app/node_modules/hapi-auth-jwt2/node_modules/jsonwebtoken/verify.js:94:10)
    at /usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:151:17
    at Array.some ()
    at /usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:150:16
    at keyFunc (/usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:134:18)
    at Object.authenticate (/usr/src/app/node_modules/hapi-auth-jwt2/lib/index.js:137:9)
    at /usr/src/app/node_modules/hapi/lib/auth.js:336:34
    at module.exports.internals.Protect.internals.Protect.run (/usr/src/app/node_modules/hapi/lib/protect.js:60:12)
    at internals.Authenticator.execute (/usr/src/app/node_modules/hapi/lib/auth.js:332:30)
    at internals.Authenticator.authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:318:21)
    at module.exports.internals.Auth.internals.Auth._authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:226:19)
    at internals.Auth.authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:197:17)
    at each (/usr/src/app/node_modules/hapi/lib/request.js:401:16)
    at iterate (/usr/src/app/node_modules/items/lib/index.js:36:13)
```

**Comment by ebarriosjr** [comment]
Please ignore this. Had a wrong configuration on the screwdriver-api jwt keys.
