### ISSUE TITLE
Local test server not starting

### ISSUE THREAD

**Issue by henderjm** [screwdriver-cd/screwdriver#2553]
**What happened**:
The screwdriver ui and api both fail on startup for different reasons.

The API fails because of a message saying bitbucket is not supported but it is listed as a supported SCM

```
api_1    | (sequelize) Warning: SQLite does not support 'INTEGER' with UNSIGNED or ZEROFILL. Plain 'INTEGER' will be used instead.
api_1    | >> Check: https://www.sqlite.org/datatype3.html
store_1  | {"level":"info","message":"Server running at http://192.168.15.27:9002","timestamp":"2021-09-06T09:20:52.744Z"}
api_1    | {"message":"Scm plugin bitbucket is not supported","level":"warn","timestamp":"2021-09-06T09:20:52.781Z"}
api_1    | /usr/src/app/node_modules/screwdriver-scm-router/index.js:43
api_1    |             throw new Error('No scm config passed in.');
api_1    |             ^
api_1    |
api_1    | Error: No scm config passed in.
api_1    |     at new ScmRouter (/usr/src/app/node_modules/screwdriver-scm-router/index.js:43:19)
api_1    |     at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-api/bin/server:87:13)
api_1    |     at Module._compile (internal/modules/cjs/loader.js:999:30)
api_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
api_1    |     at Module.load (internal/modules/cjs/loader.js:863:32)
api_1    |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
api_1    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
api_1    |     at internal/main/run_main_module.js:17:47
api_1    | npm ERR! code ELIFECYCLE
api_1    | npm ERR! errno 1
api_1    | npm ERR! screwdriver-api@4.1.84 start: `./bin/server`
api_1    | npm ERR! Exit status 1
api_1    | npm ERR!
api_1    | npm ERR! Failed at the screwdriver-api@4.1.84 start script.
api_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1    | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
api_1    |
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /root/.npm/_logs/2021-09-06T09_20_52_846Z-debug.log
```

The UI fails because of a LUA + NGINX problem

```
ui_1     | nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:101
ui_1     | 2021/09/06 09:20:48 [alert] 1#1: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
ui_1     | nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
ui_1     | 2021/09/06 09:20:48 [error] 1#1: failed to initialize Lua VM in /etc/nginx/nginx.conf:119
ui_1     | nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:119
```

**What you expected to happen**:
To have a locally running screwdriver platform

**How to reproduce it**:
`python <(curl -L https://git.io/sd-in-a-box)`

Select bitbucket as the SCM
Enter OAUTH key and secret
Select `y` when asked to run docker-compose commands

**Comment by tkyi** [comment]
At the time of comment, pinning to v4.1.135 should be a workaround.
The fix should be in production and should work now.
