### ISSUE TITLE
screwriver-request does not return proper format of error message.

### ISSUE THREAD

**Issue by sakka2** [screwdriver-cd/screwdriver#2623]
**What happened**:
[screwdriver-request](https://github.com/screwdriver-cd/request/blob/7a65a75c0b4e9109f1d1205d75bbc5e2dab547b2/index.js) seems to be supported json only as a response type.
For example, when I set response type 'buffer', error message was returned with invalid format because [JSON.stringify()](https://github.com/screwdriver-cd/request/blob/7a65a75c0b4e9109f1d1205d75bbc5e2dab547b2/index.js#L51-L53) method was used despite format of the error message was buffer.
In case of buffer, `body.message` key seems not to be recognized because the error message also returns as byte sequence.

**What you expected to happen**:
Support other response type such as 'buffer'

**How to reproduce it**:
Set the response type `buffer` and make an error.

**Comment by y-oksaku** [comment]
This problem also occurs when the response is successful.

The following happened:

- `GET /v4/builds/{buildId}/artifacts/manifest.txt`
This request throws error that
```
Error: 200 Reason "***"
    at throwError (/***/node_modules/screwdriver-request/index.js:14:17)
    at /***/node_modules/screwdriver-request/index.js:56:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CustomWorld.step (/***/acceptance-tests/features/step_definitions/private-pipeline.js:175:30) {
  statusCode: 200
}
```

- `GET /v4/builds/{buildId}/artifacts/environment.json`
However, this request succeeded.
