### ISSUE TITLE
(docs)Be more clear about minimum node version for template operations

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2687]
**What happened**:

I have a template definition with some `screwdriver.yaml` content like:

```
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - init: npm install -g screwdriver-template-main
      - env: |
          export SD_TEMPLATE_NAME=${SD_JOB_NAME#*template-}
          export SD_TEMPLATE_PATH=templates/$SD_TEMPLATE_NAME.yaml
      - validate: template-validate
      - publish: |
          if [ -z "$SD_PULL_REQUEST" ]; then
            template-publish --json --tag latest
          fi
```

The `validate` step produces:

```
$ template-validate
/usr/local/lib/node_modules/screwdriver-template-main/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/screwdriver-template-main/node_modules/got/dist/source/index.js:14:18)
```

With local knowledge, I learned that replacing `node:8` with `node:14` for `image` would resolve this, which it did.

**What you expected to happen**:

I expected either/both of `screwdriver-template-main` to warn/error on an insufficient version of node or some documentation about the minimum node version in the image.

**How to reproduce it**:

Run `validate-template` with `node:8`

**Comment by dwmarshall** [comment]
Also recommended, add a minimum node version to `engines` in `package.json` for screwdriver-template-main
