### ISSUE TITLE
Bitbucket SCM Unable to Load Screwdriver.yaml

### ISSUE THREAD

**Issue by xangxiong** [screwdriver-cd/screwdriver#2690]
**What happened**:
Bitbucket SCM 4.5.0 or newer can no longer load the screwdriver.yaml for any repo. If downgrade to Bitbucket SCM 4.4.0, screwdriver.yaml loads fine.

**What you expected to happen**:
Bitbucket SCM should be able to load the screwdriver.yaml.

**How to reproduce it**:
I am running Screwdriver API version v4.1.224, UI version v1.0.680, and Bitbucket SCM 4.5.0 (fails for 4.5.1, 4.5.2, and 4.6.0).  Once screwdriver is up and running, add a Bitbucket repo.  It will fail with the error message: "pipelineId:1: Failed to fetch screwdriver.yaml."

In case it is helpful, below is the relevant logs:

`{"level":"error","message":"pipelineId:2: Failed to fetch screwdriver.yaml. 200 Reason \"\"shared:\\n  image: test-image:latest\\n  annotations:\\n    screwdriver.cd/cpu: HIGH\\n    screwdriver.cd/ram: HIGH\\njobs:\\n  main:\\n    requires:\\n      - ~pr\\n      - ~commit\\n    steps:\\n      - setup: ./cicd/setup.sh\\n      - test: ./cicd/test.sh\\n      - build: ./cicd/build.sh\\n      - upload: ./cicd/upload.sh\\n\"\"","stack":"Error: 200 Reason \"\"shared:\\n  image: test-image:latest\\n  annotations:\\n    screwdriver.cd/cpu: HIGH\\n    screwdriver.cd/ram: HIGH\\njobs:\\n  main:\\n    requires:\\n      - ~pr\\n      - ~commit\\n    steps:\\n      - setup: ./cicd/setup.sh\\n      - test: ./cicd/test.sh\\n      - build: ./cicd/build.sh\\n      - upload: ./cicd/upload.sh\\n\"\"\n    at throwError (/usr/src/app/node_modules/screwdriver-request/index.js:14:17)\n    at /usr/src/app/node_modules/screwdriver-request/index.js:56:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","statusCode":200,"timestamp":"2022-04-01T18:29:17.583Z"}
220401/182917.583, (1648837754527:screwdriver-api-75fd9fbb86-gww5n:63:l1gqr955:10138) [request,server,error] data: Error: pipelineId:2: Failed to fetch screwdriver.yaml.
    at /usr/src/app/node_modules/screwdriver-models/lib/pipeline.js:295:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PipelineModel.sync (/usr/src/app/node_modules/screwdriver-models/lib/pipeline.js:931:30)
    at async handler (/usr/src/app/node_modules/screwdriver-api/plugins/events/create.js:231:27)
    at async exports.Manager.execute (/usr/src/app/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at async Object.internals.handler (/usr/src/app/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/usr/src/app/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:371:32)
    at async Request._execute (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:281:9)i/hapi/lib/request.js:281:9)`

**Comment by jithine** [comment]
@tkyi

**Comment by jithine** [comment]
@xangxiong can you test if 4.6.1 works for you

**Comment by xangxiong** [comment]
@jithine,

Verified on my end that 4.6.1 fixed the issue.  We can close this request.
