### ISSUE TITLE
" (HTTP code 404) no such container - No such image: screwdrivercd/launcher:stable" on triggering pipeline

### ISSUE THREAD

**Issue by QubitPi** [screwdriver-cd/screwdriver#2978]
**What happened**:

Starting a pipeline job (in [Docker Compose](https://github.com/screwdriver-cd/in-a-box)) manually results in:

<img width="1661" alt="page 1" src="https://github.com/screwdriver-cd/screwdriver/assets/16126939/1ab89161-f421-43bf-80a6-a7c5b0fb862a">

The Screwdriver API server running inside Docker logged following error trace:

```bash
2023-12-27 16:27:33 231227/082733.787, (1703665613128:1c380868d16d:19:lqnihiu8:10025) [request,server,error] data: Error: (HTTP code 404) no such container - No such image: screwdrivercd/launcher:stable 
2023-12-27 16:27:33     at /usr/src/app/node_modules/docker-modem/lib/modem.js:343:17
2023-12-27 16:27:33     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:373:7)
2023-12-27 16:27:33     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:342:5)
2023-12-27 16:27:33     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:310:16)
2023-12-27 16:27:33     at IncomingMessage.emit (node:events:529:35)
2023-12-27 16:27:33     at endReadableNT (node:internal/streams/readable:1400:12)
2023-12-27 16:27:33     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This is strange because it image [is up there](https://hub.docker.com/layers/screwdrivercd/launcher/stable/images/sha256-05423f8ca1049115b21e86a56c19bcccdb1e98b04e388848d8ebead78b49e5bf?context=explore) and I pull it to my local machine

**What you expected to happen**:

I should not see the error above

**How to reproduce it**:

1. Fork [screwdriver example app](https://github.com/screwdriver-cd-test/quickstart-generic)
2. [Turn off coverage plugin](https://github.com/screwdriver-cd/screwdriver/issues/2977#issuecomment-1870054699) and spin up a [Docker Compose instance](https://github.com/screwdriver-cd/in-a-box) (by the way I opened a bug fix [PR](https://github.com/screwdriver-cd/in-a-box/pull/8) in order for it to work)
3. Create a pipeline using the example app
4. Hit "Start" in the screenshot

**Comment by QubitPi** [comment]
Answering by myself after some digging:

I need to manually pull launcher with `docker pull screwdrivercd/launcher:stable` for my local Docker Compose to pick it up

**Comment by jithine** [comment]
Thank you for the fix. Closing this issue.
