### ISSUE TITLE
Github plugin test fails at before each hook

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#308]
Been seeing this more often now:

```
github plugin test "before each" hook for "returns 204":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at server.register (test/plugins/webhooks/github.test.js:109:13)
      at process.nextTick (node_modules/hapi/node_modules/hoek/lib/index.js:854:22)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Increased the timeout to 3000ms helped but then can still hit it randomly. Cannot reproduce locally.

**Comment by stjohnjohnson** [comment]
I'll look into this.

**Comment by stjohnjohnson** [comment]
I wonder if it's related to the CPU limits here: https://github.com/screwdriver-cd/kubernetes/blob/master/limits.yaml#L12-L20

**Comment by d2lam** [comment]
We are fine with increasing the timeout to 3000. Doesn't happen anymore. Will close this issue and reopen if we see it again.
