### ISSUE TITLE
Cannot login, token not allowed

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#48]
Attempting to login gives the following error:
```
160727/054041.769, [error] message: "token" is not allowed stack: ValidationError: "token" is not allowed
    at Object.exports.process (/usr/src/app/node_modules/joi/lib/errors.js:154:19)
    at _validateWithOptions (/usr/src/app/node_modules/joi/lib/any.js:601:31)
    at root.validate (/usr/src/app/node_modules/vogels/node_modules/joi/lib/index.js:102:23)
    at Schema.validate (/usr/src/app/node_modules/vogels/lib/schema.js:173:14)
    at /usr/src/app/node_modules/vogels/lib/table.js:160:30
    at /usr/src/app/node_modules/vogels/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous> (/usr/src/app/node_modules/vogels/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Token is not in the data model: https://github.com/screwdriver-cd/data-schema/blob/master/models/user.js

**Comment by stjohnjohnson** [comment]
Looks like it's working now.
