### ISSUE TITLE
Docker Swarm configuration for executor confusion

### ISSUE THREAD

**Issue by lgfausak** [screwdriver-cd/screwdriver#910]
**What happened**:
I can't get docker swarm configured

**What you expected to happen**:

**How to reproduce it**:
I put this in the local.yaml of the api:
```executor:
  plugin: docker
  docker:
    options:
      docker:
        socketPath: /var/run/docker.sock
      launchVersion: stable
```
Then I *can* launch jobs against a single docker engine.  However, if I run this:
```executor:
  plugin: docker
  docker:
    options:
      docker:
         host: 100.5.70.13
         port: 2377
         version: 'v1.32'
      launchVersion: stable
```
My pipelines will not run. I get an error message on the ui `Parse Error` and the api produces this on stdout:
```180306/154438.588, [response] https://sdapi.dev.vzwops.com: [1;34moptions[0m /v4/events {} [32m200[0m (4ms)
180306/154440.310, [response,api] https://sdapi.dev.vzwops.com: [1;32mget[0m /v4/status {} [32m200[0m (4ms)
180306/154447.027, (1520351078747:895e2bf144f8:1:jeftmgt4:10090) [request,server,error] data: Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
180306/154438.747, [response,api,events] https://sdapi.dev.vzwops.com: [1;33mpost[0m /v4/events {} [31m500[0m (8291ms)
180306/154450.319, [response,api] https://sdapi.dev.vzwops.com: [1;32mget[0m /v4/status {} [32m200[0m (6ms)
180306/154500.325, [response,api] https://sdapi.dev.vzwops.com: [1;32mget[0m /v4/status {} [32m200[0m (15ms)
```
I think the basic issue is that when I look at the docker executor, it says it supports docker swarm mode.  I just can't figure out how to configure swarm mode.

**Comment by jithin1987** [comment]
References to docker swarm has been removed from `executor-docker`. It does not have capability to work with swarm.
