### ISSUE TITLE
500 Response from github webhook close event

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#96]
160813/000203.442, [request,webhook-github,2a050f80-60e9-11e6-900d-ae68a135de5f] data: Received event pull_request
160813/000203.442, [request,webhook-github,2a050f80-60e9-11e6-900d-ae68a135de5f] data: PR #49 closed for git@github.com:screwdriver-cd/models.git#master
160813/000203.574, [request,server] data: ValidationException: Invalid KeyConditionExpression: An expression attribute value used in expression is not defined; attribute value: :jobId
    at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
160813/000203.356, [response] http://0.0.0.0:8080: post /v3/webhooks/github {} 500 (220ms)

**Comment by FenrirUnbound** [comment]
Hypothesis:
It's a `.scan()` against the secondary index (https://github.com/screwdriver-cd/datastore-dynamodb/blob/master/index.js#L170) when it should be a .query()` operation.

**Comment by jer** [comment]
More info about the close request:

Request URL: http://a4677c9873c9611e6aa7102b92f75d5c-1135862614.us-west-2.elb.amazonaws.com/v3/webhooks/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/4d0fdb7
X-GitHub-Delivery: 6d8b9380-630c-11e6-82a3-6e3d08f12f78
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=0f2ca6298c63f0f5cdc517eb3cb57cac26d0800b

**Comment by stjohnjohnson** [comment]
@nkatzman any ideas with this?

**Comment by nkatzman** [comment]
Is this still an issue?

**Comment by stjohnjohnson** [comment]
Unable to reproduce.
